### PR TITLE
Added D20106 profile and tested on real device

### PR DESCRIPTION
**Pull request by rdruilhe**
Hello,

We are using your EnOcean library with a new profile (the D20106). Thus, it could be interesting for everyone to add it in the main branch.

We performed some tests on the physical device providing this profile and we did not find any bugs during runtime.

I hope it can help someone else.

Thanks,

Best regards.

### CODE REVIEW

**Review by dbonino — CHANGES_REQUESTED** [review]
Thank you very much for your contribution. 
As coding convention I do prefer to have channel identifiers declared as static variables. I've noticed that you are registering the EEP26Switching on =0x00 which is ALL_OUTPUT_CHANNELS while registering the EEP26EnergyMeasurement on 31 (0x1F) which correponds to INPUT_CHANNEL in the EEP26 specification. Would you mind defining the missing static variable and then using it instead of "magic numbers" for the channel identifiers? Thank you very much. Dario.

**Comment by rdruilhe** [comment]
Hello Dario,

I can set the channel identifiers as static variable. 

Regarding the values of the channels, I used the "trial and error" method. The device we used to test the profile is the W1R16FP from General Electric and there is no documentation about it. I just know that this is a D2.01.06 device. So, the value of the channels was set based on our experimentations.

Thus, I don't know if this profile should be integrated to the main library after all, because the channels might be defined only for this device (and not the others devices with the same profile). But I haven't tried others devices with the same profile, so I don't know.

So, is it interesting for you to push this kind of profile?

**Comment by dbonino** [comment]
Definitely it is interesting for us to merge this pull request. As soon as you'll set the Chanel identifiers as static variables i will accept the request! Again thank you!

**Comment by rdruilhe** [comment]
The changes have been done. I hope everything is correct now.

**Comment by dbonino** [comment]
Dear @rdruilhe,
I have merged the pull request and re-factored your static variable declaration to reflect the terminology used in the EEP26 specification. Could you just check if the updated version still works?

best regards
Dario

**Comment by rdruilhe** [comment]
Hello @dbonino,

I just checked the new version. It works well. Thank you for the merge.

Best regards.

**Pull request merged**
