### PR TITLE
FIX: destructive array copy

### LINKED ISSUE #2: ESP3Packet.java - bad array copy
I just fixed an array copy operation in the quoted class.
Pull request coming soon.

### PR DESCRIPTION
**Pull request by IOOOTARobby**
Should fix #2

### CODE REVIEW

**Comment by dbonino** [comment]
@IOOOTARobby thanks very much for your contribution, sorry for the "stupid" mistake.
@luigidr thanks for quickly accepting the request, I was accepting it almost at the same time

**Comment by IOOOTARobby** [comment]
@dbonino my pleasure. Thank you for this very well made piece of software

**Comment by dbonino** [comment]
@IOOOTARobby sorry for bothering again, I've compacted a bit the array copy in just one line using Arrays.copyOf(), if you want to pull this last version...

**Comment by IOOOTARobby** [comment]
@dbonino sure, just done! 👍

**Pull request merged**
